import { Search, X } from "lucide-react";
import type { NotificationCategory, NotificationFilters, NotificationPriority } from "@/features/notifications/notification-types";
import { categoryLabel, titleCase } from "@/features/notifications/notification-utils";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const categories: NotificationCategory[] = ["system", "rescue", "medical", "volunteer", "adoption", "inventory", "donation", "campaign"];
const priorities: NotificationPriority[] = ["critical", "high", "normal", "low"];

export function NotificationFilters({ filters, onChange, onClear, activeCount }: { filters: NotificationFilters; onChange: (next: Partial<NotificationFilters>) => void; onClear: () => void; activeCount: number }) {
  return <Card><CardContent className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-[minmax(18rem,1fr)_10rem_9rem_9rem_auto]"><label className="relative md:col-span-2 xl:col-span-1"><span className="sr-only">Search notifications</span><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={filters.search} onChange={(event) => onChange({ search: event.target.value })} placeholder="Search notifications" /></label><Select value={filters.category} onValueChange={(category) => onChange({ category: category as NotificationFilters["category"] })}><SelectTrigger aria-label="Filter category"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{categories.map((category) => <SelectItem key={category} value={category}>{categoryLabel(category)}</SelectItem>)}</SelectContent></Select><Select value={filters.readState} onValueChange={(readState) => onChange({ readState: readState as NotificationFilters["readState"] })}><SelectTrigger aria-label="Filter read state"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All states</SelectItem><SelectItem value="unread">Unread</SelectItem><SelectItem value="read">Read</SelectItem></SelectContent></Select><Select value={filters.priority} onValueChange={(priority) => onChange({ priority: priority as NotificationFilters["priority"] })}><SelectTrigger aria-label="Filter priority"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All priorities</SelectItem>{priorities.map((priority) => <SelectItem key={priority} value={priority}>{titleCase(priority)}</SelectItem>)}</SelectContent></Select><Select value={filters.sort} onValueChange={(sort) => onChange({ sort: sort as NotificationFilters["sort"] })}><SelectTrigger aria-label="Sort notifications"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="newest">Newest first</SelectItem><SelectItem value="oldest">Oldest first</SelectItem><SelectItem value="priority">Priority first</SelectItem></SelectContent></Select><Button variant="ghost" size="sm" onClick={onClear} disabled={!activeCount}><X className="mr-1 h-4 w-4" /> Clear{activeCount ? ` (${activeCount})` : ""}</Button></CardContent></Card>;
}
