import { useMemo, useState } from "react";
import { Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";
import { AlertTriangle, Search, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDate } from "@/lib/utils";

type Volunteer = { id: string; totalCases: number; activeCases: number; highPriorityCases: number; lastAssignedAt: string | null };
type RescueCase = { id: number; caseNumber: string; animalName: string; species: string; status: string; priority: string; rescueLocation: string };
const workload = (value: number) => value >= 8 ? "overloaded" : value >= 5 ? "busy" : "available";
const variant = (value: string) => value === "overloaded" ? "destructive" : value === "busy" ? "warning" : "success";

function VolunteerCard({ volunteer }: { volunteer: Volunteer }) {
  const [open, setOpen] = useState(false); const state = workload(volunteer.activeCases);
  const casesQuery = useQuery({ queryKey: ["volunteer-cases", volunteer.id], queryFn: () => customFetch<RescueCase[]>(`/api/rescue-cases/assigned/${encodeURIComponent(volunteer.id)}`), enabled: open });
  return <Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{volunteer.id}</CardTitle><CardDescription>{volunteer.lastAssignedAt ? `Last assigned ${formatDate(volunteer.lastAssignedAt)}` : "No assignment date available"}</CardDescription></div><Badge variant={variant(state) as never}>{state}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-3 gap-2 text-center"><div><p className="text-xl font-bold">{volunteer.activeCases}</p><p className="text-xs text-muted-foreground">Active</p></div><div><p className="text-xl font-bold">{volunteer.highPriorityCases}</p><p className="text-xs text-muted-foreground">High priority</p></div><div><p className="text-xl font-bold">{volunteer.totalCases}</p><p className="text-xs text-muted-foreground">Total</p></div></div><div><div className="mb-1 flex justify-between text-xs text-muted-foreground"><span>Workload</span><span>{Math.min(volunteer.activeCases, 8)} / 8</span></div><Progress value={Math.min(100, volunteer.activeCases * 12.5)} className="h-2" /></div>{state === "overloaded" ? <p className="rounded-md bg-destructive/10 p-2 text-xs text-destructive">This volunteer has 8 or more active cases. Consider reassigning a case.</p> : null}<Button className="w-full" variant="outline" onClick={() => setOpen((value) => !value)} aria-expanded={open}>{open ? "Hide assigned cases" : "View assigned cases"}</Button>{open ? <div className="space-y-2 border-t pt-3">{casesQuery.isLoading ? <Skeleton className="h-16" /> : casesQuery.isError ? <p className="text-sm text-destructive">Assigned cases could not be loaded.</p> : casesQuery.data?.length ? casesQuery.data.map((item) => <Link key={item.id} href={`/rescue-cases/${item.id}`} className="block rounded border p-2 text-sm hover:bg-muted"><div className="flex justify-between gap-2"><span className="font-medium">{item.caseNumber}</span><span className="capitalize text-muted-foreground">{item.priority}</span></div><p className="truncate text-muted-foreground">{item.animalName} · {item.rescueLocation}</p></Link>) : <p className="text-sm text-muted-foreground">No cases are currently assigned.</p>}</div> : null}</CardContent></Card>;
}

export function Volunteers() {
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState<"all" | "available" | "busy" | "overloaded">("all");
  const volunteersQuery = useQuery({ queryKey: ["rescue-volunteers"], queryFn: () => customFetch<Volunteer[]>("/api/rescue-volunteers") });
  const volunteers = useMemo(() => (volunteersQuery.data ?? []).filter((item) => (filter === "all" || workload(item.activeCases) === filter) && item.id.toLowerCase().includes(search.toLowerCase())), [volunteersQuery.data, search, filter]);
  const overloaded = volunteersQuery.data?.filter((item) => workload(item.activeCases) === "overloaded").length ?? 0;
  return <main className="flex-1 space-y-6 p-4 sm:p-6 lg:p-8"><header><p className="text-sm font-medium text-primary">Rescue operations</p><h1 className="font-serif text-3xl font-bold text-primary">Volunteer assignments</h1><p className="mt-1 text-muted-foreground">Monitor active rescue workload using staff members already assigned to cases.</p></header><section className="grid gap-4 sm:grid-cols-3"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Assigned volunteers</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{volunteersQuery.data?.length ?? 0}</CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Active workload</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{volunteersQuery.data?.reduce((sum, item) => sum + item.activeCases, 0) ?? 0}</CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Overloaded</CardTitle></CardHeader><CardContent className="text-2xl font-bold text-destructive">{overloaded}</CardContent></Card></section><Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search employee ID" aria-label="Search volunteers" /></div><div className="flex gap-2">{(["all", "available", "busy", "overloaded"] as const).map((state) => <Button key={state} size="sm" variant={filter === state ? "secondary" : "outline"} onClick={() => setFilter(state)} className="capitalize">{state}</Button>)}</div></CardContent></Card>{volunteersQuery.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((key) => <Skeleton key={key} className="h-72" />)}</div> : volunteersQuery.isError ? <Card><CardContent className="flex flex-col items-center gap-3 p-12 text-center"><AlertTriangle className="h-8 w-8 text-destructive" /><p>Volunteer workload could not be loaded.</p><Button variant="outline" onClick={() => volunteersQuery.refetch()}>Try again</Button></CardContent></Card> : volunteers.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{volunteers.map((volunteer) => <VolunteerCard key={volunteer.id} volunteer={volunteer} />)}</div> : <Card><CardContent className="flex flex-col items-center gap-3 p-12 text-center"><UsersRound className="h-8 w-8 text-muted-foreground" /><p className="font-medium">No assigned volunteers found</p><p className="text-sm text-muted-foreground">Assign a staff member from a rescue case to start tracking workload.</p><Link href="/rescue-cases"><Button>Open rescue cases</Button></Link></CardContent></Card>}</main>;
}
