import type { FormEvent, ReactNode } from "react";
import { AlertCircle, ClipboardList, MapPin, Stethoscope, UserRound } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { rescuePriorities, rescueStatuses, rescueTypes, type RescueCaseForm } from "@/features/rescue/types";
import { statusLabel, validateCaseForm } from "@/features/rescue/utils";

type Props = { form: RescueCaseForm; onChange: (next: RescueCaseForm) => void; onSubmit: (event: FormEvent) => void; submitting?: boolean; submitLabel: string; onCancel?: () => void };
type FieldErrors = Partial<Record<keyof RescueCaseForm, string>>;

function FormSection({ title, icon: Icon, children }: { title: string; icon: typeof ClipboardList; children: ReactNode }) {
  return <section className="space-y-4 rounded-lg border bg-card p-4"><div className="flex items-center gap-2 border-b pb-3"><Icon className="h-4 w-4 text-primary" /><h3 className="font-medium">{title}</h3></div>{children}</section>;
}
function TextField({ label, value, onChange, error, required = false, type = "text", placeholder, min }: { label: string; value: string | number; onChange: (value: string) => void; error?: string; required?: boolean; type?: string; placeholder?: string; min?: string }) {
  const id = `rescue-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
  return <div className="space-y-1.5"><Label htmlFor={id}>{label}{required ? <span className="text-destructive"> *</span> : null}</Label><Input id={id} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} required={required} type={type} min={min} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} />{error ? <p id={`${id}-error`} className="flex items-center gap-1 text-xs text-destructive"><AlertCircle className="h-3 w-3" />{error}</p> : null}</div>;
}

export function RescueCaseForm({ form, onChange, onSubmit, submitting, submitLabel, onCancel }: Props) {
  const errors: FieldErrors = validateCaseForm(form);
  const update = <K extends keyof RescueCaseForm>(key: K, value: RescueCaseForm[K]) => onChange({ ...form, [key]: value });
  const submit = (event: FormEvent) => { if (Object.keys(errors).length > 0) { event.preventDefault(); return; } onSubmit(event); };
  return <form className="space-y-5" noValidate onSubmit={submit}>
    {Object.keys(errors).length > 0 ? <Alert variant="destructive"><AlertCircle className="h-4 w-4" /><AlertDescription>Complete the highlighted fields before saving this rescue case.</AlertDescription></Alert> : null}
    <FormSection title="Case and animal" icon={ClipboardList}><div className="grid gap-4 sm:grid-cols-2"><TextField label="Case number" required value={form.caseNumber} error={errors.caseNumber} placeholder="WH-RC-2026-001" onChange={(value) => update("caseNumber", value)} /><TextField label="Animal name" required value={form.animalName} error={errors.animalName} placeholder="If known" onChange={(value) => update("animalName", value)} /><TextField label="Species" required value={form.species} error={errors.species} placeholder="e.g. Indian pangolin" onChange={(value) => update("species", value)} /><div className="space-y-1.5"><Label>Rescue type</Label><Select value={form.rescueType} onValueChange={(value) => update("rescueType", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{rescueTypes.map((type) => <SelectItem key={type} value={type}>{statusLabel(type)}</SelectItem>)}</SelectContent></Select></div></div></FormSection>
    <FormSection title="Report and location" icon={MapPin}><div className="grid gap-4 sm:grid-cols-2"><TextField label="Rescue location" required value={form.rescueLocation} error={errors.rescueLocation} placeholder="Landmark, reserve, village, or coordinates" onChange={(value) => update("rescueLocation", value)} /><TextField label="Reported by" required value={form.reportedBy} error={errors.reportedBy} placeholder="Reporter name or organisation" onChange={(value) => update("reportedBy", value)} /><TextField label="Contact information" required value={form.contactInformation} error={errors.contactInformation} placeholder="Phone or email" onChange={(value) => update("contactInformation", value)} /><TextField label="Reported date and time" required type="datetime-local" value={form.reportedAt} error={errors.reportedAt} onChange={(value) => update("reportedAt", value)} /><TextField label="Rescue date and time" required type="datetime-local" value={form.rescueDate} error={errors.rescueDate} onChange={(value) => update("rescueDate", value)} /></div></FormSection>
    <FormSection title="Care and coordination" icon={Stethoscope}><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Status</Label><Select value={form.status} onValueChange={(value) => update("status", value as RescueCaseForm["status"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{rescueStatuses.map((status) => <SelectItem key={status} value={status}>{statusLabel(status)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Priority</Label><Select value={form.priority} onValueChange={(value) => update("priority", value as RescueCaseForm["priority"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{rescuePriorities.map((priority) => <SelectItem key={priority} value={priority}>{statusLabel(priority)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Severity</Label><Select value={form.severity} onValueChange={(value) => update("severity", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{rescuePriorities.map((severity) => <SelectItem key={severity} value={severity}>{statusLabel(severity)}</SelectItem>)}</SelectContent></Select></div><TextField label="Estimated cost" type="number" min="0" value={form.estimatedCost} error={errors.estimatedCost} onChange={(value) => update("estimatedCost", Number(value))} /></div><div className="mt-4 space-y-1.5"><Label htmlFor="condition">Condition<span className="text-destructive"> *</span></Label><Input id="condition" required value={form.condition} aria-invalid={Boolean(errors.condition)} onChange={(event) => update("condition", event.target.value)} placeholder="Visible injuries, mobility, hydration, behaviour" />{errors.condition ? <p className="text-xs text-destructive">{errors.condition}</p> : null}</div><div className="mt-4 space-y-1.5"><Label htmlFor="description">Description<span className="text-destructive"> *</span></Label><Textarea id="description" required rows={5} value={form.description} aria-invalid={Boolean(errors.description)} onChange={(event) => update("description", event.target.value)} placeholder="Document the circumstances, risks, observations, and next steps." />{errors.description ? <p className="text-xs text-destructive">{errors.description}</p> : null}</div></FormSection>
    <FormSection title="Assignment" icon={UserRound}><TextField label="Assigned employee ID" value={form.assignedEmployeeId} placeholder="Leave empty when unassigned" onChange={(value) => update("assignedEmployeeId", value)} /></FormSection>
    <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">{onCancel ? <Button type="button" variant="outline" onClick={onCancel}>Cancel</Button> : null}<Button type="submit" disabled={submitting}>{submitting ? "Saving…" : submitLabel}</Button></div>
  </form>;
}
