import { ArrowRight, HeartHandshake, HeartPulse, Package, PawPrint, UsersRound, Wallet } from "lucide-react";
import { Link } from "wouter";
import type { AdoptionDashboard, AdoptionApplication, DonationAnalytics, InventoryDashboard, InventoryItem, MedicalItem, RescueCase, VolunteerWorkload } from "@/features/command-center/types";
import { inventoryState, titleCase, workloadState } from "@/features/command-center/utils";
import { formatCurrency, formatDate } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { DashboardEmptyState } from "./dashboard-states";

function PanelHeader({ icon: Icon, title, description, href, action = "Open workspace" }: { icon: typeof PawPrint; title: string; description: string; href: string; action?: string }) {
  return <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0"><div><CardTitle className="flex items-center gap-2"><Icon className="h-5 w-5 text-primary" /> {title}</CardTitle><CardDescription className="mt-1">{description}</CardDescription></div><Button asChild variant="ghost" size="sm" className="shrink-0"><Link href={href} aria-label={`${action}: ${title}`}><ArrowRight className="h-4 w-4" /></Link></Button></CardHeader>;
}

export function RescueOverview({ cases, activeCases, criticalCases }: { cases: RescueCase[]; activeCases: RescueCase[]; criticalCases: RescueCase[] }) {
  return <Card><PanelHeader icon={PawPrint} title="Rescue overview" description="Live field-case status and escalation." href="/rescue-cases" /><CardContent><div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-lg bg-muted/60 p-3"><p className="font-serif text-2xl font-bold">{cases.length}</p><p className="mt-1 text-xs text-muted-foreground">In view</p></div><div className="rounded-lg bg-primary/10 p-3"><p className="font-serif text-2xl font-bold text-primary">{activeCases.length}</p><p className="mt-1 text-xs text-muted-foreground">Active</p></div><div className="rounded-lg bg-destructive/10 p-3"><p className="font-serif text-2xl font-bold text-destructive">{criticalCases.length}</p><p className="mt-1 text-xs text-muted-foreground">High / critical</p></div></div><div className="mt-5 space-y-3">{criticalCases.slice(0, 3).map((item) => <Link key={item.id} href={`/rescue-cases/${item.id}`} className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm transition-colors hover:bg-muted"><span className="min-w-0"><span className="block truncate font-medium">{item.animalName}</span><span className="block truncate text-xs text-muted-foreground">{item.caseNumber} · {item.rescueLocation}</span></span><Badge variant={item.priority === "critical" ? "destructive" : "warning"}>{titleCase(item.priority)}</Badge></Link>)}</div>{!criticalCases.length ? <p className="mt-5 text-sm text-muted-foreground">No high-priority rescue cases match this view.</p> : null}</CardContent></Card>;
}

export function MedicalOverview({ items, underTreatment }: { items: MedicalItem[]; underTreatment: MedicalItem[] }) {
  const followUps = items.filter((item) => item.record.followUpDate).sort((first, second) => new Date(first.record.followUpDate!).getTime() - new Date(second.record.followUpDate!).getTime());
  return <Card><PanelHeader icon={HeartPulse} title="Medical & recovery" description="Treatment state and scheduled follow-ups." href="/medical-recovery" /><CardContent><div className="flex items-baseline justify-between"><div><p className="font-serif text-3xl font-bold">{underTreatment.length}</p><p className="text-xs text-muted-foreground">animals under treatment</p></div><div className="text-right"><p className="font-serif text-2xl font-bold text-primary">{items.filter((item) => item.record.medicalStatus === "recovering").length}</p><p className="text-xs text-muted-foreground">recovering</p></div></div><div className="mt-5 space-y-3">{followUps.slice(0, 3).map((item) => <Link key={item.record.id} href={`/rescue-cases/${item.rescueCase.id}`} className="block rounded-md border p-3 transition-colors hover:bg-muted"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{item.rescueCase.animalName}</p><Badge variant={item.record.medicalStatus === "critical" ? "destructive" : "warning"}>{titleCase(item.record.medicalStatus)}</Badge></div><p className="mt-1 truncate text-xs text-muted-foreground">Follow-up {item.record.followUpDate ? formatDate(item.record.followUpDate) : "not scheduled"} · {item.record.diagnosis}</p></Link>)}</div>{!followUps.length ? <p className="mt-5 text-sm text-muted-foreground">No scheduled medical follow-ups match this view.</p> : null}</CardContent></Card>;
}

export function AdoptionOverview({ dashboard, applications }: { dashboard: AdoptionDashboard; applications: AdoptionApplication[] }) {
  const pending = applications.filter((item) => item.status === "pending_review");
  return <Card><PanelHeader icon={HeartHandshake} title="Adoption overview" description="Placement activity and application decisions." href="/adoptions" /><CardContent><div className="grid grid-cols-3 gap-3 text-center"><div><p className="font-serif text-2xl font-bold">{dashboard.availableForAdoption}</p><p className="mt-1 text-xs text-muted-foreground">Available</p></div><div><p className="font-serif text-2xl font-bold text-amber-700">{pending.length}</p><p className="mt-1 text-xs text-muted-foreground">Pending</p></div><div><p className="font-serif text-2xl font-bold text-emerald-700">{dashboard.completedAdoptions}</p><p className="mt-1 text-xs text-muted-foreground">Placed</p></div></div><div className="mt-5 space-y-2">{pending.slice(0, 3).map((item) => <Link key={item.id} href="/adoptions" className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm transition-colors hover:bg-muted"><span className="min-w-0"><span className="block truncate font-medium">{item.animalName}</span><span className="block truncate text-xs text-muted-foreground">{item.applicantName} · {item.applicationNumber}</span></span><Badge variant="warning">Review</Badge></Link>)}</div>{!pending.length ? <p className="mt-5 text-sm text-muted-foreground">No pending applications match this view.</p> : null}</CardContent></Card>;
}

export function VolunteerOverview({ volunteers }: { volunteers: VolunteerWorkload[] }) {
  const workload = [...volunteers].sort((first, second) => second.activeCases - first.activeCases);
  return <Card><PanelHeader icon={UsersRound} title="Volunteer workload" description="Assignment pressure across the rescue team." href="/volunteers" /><CardContent>{workload.length ? <div className="space-y-4">{workload.slice(0, 5).map((item) => { const state = workloadState(item.activeCases); return <Link key={item.id} href="/volunteers" className="block rounded-md transition-colors hover:bg-muted"><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">{item.id}</span><Badge variant={state === "overloaded" ? "destructive" : state === "busy" ? "warning" : "success"}>{item.activeCases} active</Badge></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className={state === "overloaded" ? "h-full bg-destructive" : state === "busy" ? "h-full bg-amber-500" : "h-full bg-primary"} style={{ width: `${Math.min(item.activeCases / 8 * 100, 100)}%` }} /></div></Link>; })}</div> : <DashboardEmptyState title="No volunteer workloads" detail="Assign responders to rescue cases to populate workload information." />}</CardContent></Card>;
}

export function InventoryOverview({ dashboard, items }: { dashboard: InventoryDashboard; items: InventoryItem[] }) {
  const alerts = items.filter((item) => inventoryState(item) !== "in_stock");
  return <Card><PanelHeader icon={Package} title="Inventory availability" description="Stock health for field and medical supplies." href="/inventory" /><CardContent><div className="grid grid-cols-3 gap-3 text-center"><div><p className="font-serif text-2xl font-bold">{dashboard.inStock}</p><p className="mt-1 text-xs text-muted-foreground">In stock</p></div><div><p className="font-serif text-2xl font-bold text-amber-700">{dashboard.lowStock}</p><p className="mt-1 text-xs text-muted-foreground">Low stock</p></div><div><p className="font-serif text-2xl font-bold text-destructive">{dashboard.outOfStock}</p><p className="mt-1 text-xs text-muted-foreground">Out of stock</p></div></div><div className="mt-5 space-y-2">{alerts.slice(0, 3).map((item) => <Link key={item.id} href="/inventory" className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm transition-colors hover:bg-muted"><span className="min-w-0"><span className="block truncate font-medium">{item.name}</span><span className="block text-xs text-muted-foreground">{item.quantity} {item.unit} · minimum {item.minimumQuantity}</span></span><Badge variant={inventoryState(item) === "out_of_stock" ? "destructive" : "warning"}>{titleCase(inventoryState(item))}</Badge></Link>)}</div>{!alerts.length ? <p className="mt-5 text-sm text-muted-foreground">No low-stock items match this view.</p> : null}</CardContent></Card>;
}

export function DonationOverview({ analytics }: { analytics: DonationAnalytics }) {
  return <Card><PanelHeader icon={Wallet} title="Donations & impact" description="Contribution totals and the latest confirmed records." href="/analytics" action="Open donation analytics" /><CardContent><div className="grid grid-cols-2 gap-3"><div><p className="font-serif text-2xl font-bold text-primary">{formatCurrency(analytics.summary.totalAmount)}</p><p className="mt-1 text-xs text-muted-foreground">{analytics.summary.totalDonations} donations</p></div><div><p className="font-serif text-2xl font-bold">{formatCurrency(analytics.summary.averageAmount)}</p><p className="mt-1 text-xs text-muted-foreground">Average gift</p></div></div><div className="mt-5 space-y-3">{analytics.recentDonations.slice(0, 3).map((item) => <Link key={item.id} href="/donations" className="block rounded-md border p-3 transition-colors hover:bg-muted"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{item.donorName}</p><p className="shrink-0 text-sm font-semibold">{formatCurrency(item.amount)}</p></div><p className="mt-1 truncate text-xs text-muted-foreground">{item.campaignName} · {formatDate(item.donatedAt)}</p></Link>)}</div>{!analytics.recentDonations.length ? <p className="mt-5 text-sm text-muted-foreground">No donations match the selected date range.</p> : null}</CardContent></Card>;
}
